<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'BjyProfiler\Module'                             => __DIR__ . '/Module.php',
  'BjyProfiler\Db\Adapter\ProfilingAdapter'        => __DIR__ . '/src/BjyProfiler/Db/Adapter/ProfilingAdapter.php',
  'BjyProfiler\Db\Adapter\ProfilingAdapterFactory' => __DIR__ . '/src/BjyProfiler/Db/Adapter/ProfilingAdapterFactory.php',
  'BjyProfiler\Db\Profiler\LoggingProfiler'        => __DIR__ . '/src/BjyProfiler/Db/Profiler/LoggingProfiler.php',
  'BjyProfiler\Db\Profiler\Profiler'               => __DIR__ . '/src/BjyProfiler/Db/Profiler/Profiler.php',
  'BjyProfiler\Db\Profiler\Query'                  => __DIR__ . '/src/BjyProfiler/Db/Profiler/Query.php',
);
